alias ..='cd ..'
alias ....='cd ../..'
alias .....='cd ../../..'
alias ......='cd ../../../..'
alias today='garden $nickname' 
alias so='source ~/.bashrc && cp $HOME/.dotfiles/.bashrc ~'
alias ioversion='iojs --version'
alias vscode='$HOME/.VSCode/Code'
