
source ~/.dotfiles/.funcs/replace.sh
source ~/.dotfiles/.funcs/mkdir.sh
source ~/.dotfiles/.funcs/subl.sh
source ~/.dotfiles/.funcs/atom.sh
source ~/.dotfiles/.funcs/open.sh
source ~/.dotfiles/.funcs/compile.sh
source ~/.dotfiles/.funcs/iotest.sh
source ~/.dotfiles/.funcs/circletest.sh
source ~/.dotfiles/.funcs/appveyortest.sh
source ~/.dotfiles/.funcs/badge.sh
source ~/.dotfiles/.funcs/gitssh.sh
source ~/.dotfiles/.funcs/testhook.sh
source ~/.dotfiles/.funcs/youtube.sh
source ~/.dotfiles/.funcs/youtubelist.sh
source ~/.dotfiles/.funcs/zip.sh
source ~/.dotfiles/.funcs/convertlist.sh
source ~/.dotfiles/.funcs/gcn.sh
source ~/.dotfiles/.funcs/fln.sh
source ~/.dotfiles/.funcs/blur.sh
source ~/.dotfiles/.funcs/javacompile.sh
source ~/.dotfiles/.funcs/cleartitle.sh
source ~/.dotfiles/.funcs/rename.sh
source ~/.dotfiles/.funcs/mp3name.sh
source ~/.dotfiles/.funcs/static.sh
source ~/.dotfiles/.funcs/upstream.sh
source ~/.dotfiles/.funcs/gitalias.sh
source ~/.dotfiles/.funcs/gitrecentbranches.sh
source ~/.dotfiles/.funcs/gopackage.sh
source ~/.dotfiles/.funcs/cop.sh
source ~/.dotfiles/.funcs/parlaklik.sh
source ~/.dotfiles/.funcs/goversion.sh
source ~/.dotfiles/.funcs/todocount.sh
source ~/.dotfiles/.funcs/private-npm.sh
source ~/.dotfiles/.funcs/say.sh
source ~/.dotfiles/.funcs/joinimage.sh
source ~/.dotfiles/.funcs/sconvert.sh
source ~/.dotfiles/.funcs/exportvideo.sh
source ~/.dotfiles/.funcs/cutvideo.sh
source ~/.dotfiles/.funcs/dropboxcp.sh