source ~/.dotfiles/.funcs/replace.sh
source ~/.dotfiles/.funcs/mkdir.sh
source ~/.dotfiles/.funcs/subl.sh
source ~/.dotfiles/.funcs/atom.sh
source ~/.dotfiles/.funcs/open.sh
source ~/.dotfiles/.funcs/compile.sh
source ~/.dotfiles/.funcs/iotest.sh
source ~/.dotfiles/.funcs/circletest.sh
source ~/.dotfiles/.funcs/appveyortest.sh
source ~/.dotfiles/.funcs/badge.sh
source ~/.dotfiles/.funcs/gitssh.sh
source ~/.dotfiles/.funcs/testhook.sh
source ~/.dotfiles/.funcs/youtube.sh
source ~/.dotfiles/.funcs/youtubelist.sh
source ~/.dotfiles/.funcs/zip.sh
source ~/.dotfiles/.funcs/convertlist.sh
source ~/.dotfiles/.funcs/gcn.sh
source ~/.dotfiles/.funcs/fln.sh
source ~/.dotfiles/.funcs/blur.sh
source ~/.dotfiles/.funcs/javacompile.sh